### PR TITLE
implement validation on email and username

### PR DESCRIPTION
**Pull request by gauravsahu21**
#12  #11

### CODE REVIEW

**Comment by honganhcs** [comment]
Hi Gaurav, thank you for your interest and enthusiasm for our project! We would like to schedule a Zoom meeting with you to discuss how you can contribute. We will email you shortly!

**Comment by honganhcs** [comment]
Please also note that you should not merge any PRs that have not been approved by @nbvannhi or me (including this one)! We will tell you more about the development process we follow in our meeting :D Thanks!

**Comment by gauravsahu21** [comment]
Okay, @honganhcs  I will wait for the zoom meeting.

**Comment by honganhcs** [comment]
closing PR as there have been extensive updates to the SignUp page in the master branch

**Pull request closed without merging**
